### ISSUE TITLE
Fast transition not happening

### ISSUE THREAD

**Issue by jeetu28** [graingert/802.11r#1]
I am trying to have 80211r setup with wpa_supplicant and aruba Access Points. Config is below:

country=FR
network={
        scan_ssid=1
        ssid="XXXXX"
        key_mgmt=WPA-EAP FT-EAP
        ca_cert="/etc/luci-uploads/CA_CERTIFICATE"
        identity="mar"
        anonymous_identity="mar"
        client_cert="/etc/luci-uploads/userCert.pem"
        private_key="/etc/luci-uploads/userKey.pem"
        private_key_passwd="**********"
        eap=TLS
        proto=RSN
        beacon_int=100
        scan_freq=5540 5560 5580 5600
        bgscan="simple:3:-58:3600"
}
fast_reauth=1
ignore_old_scan_res=1
filter_ssids=1
eapol_version=2

It is authenticating again and again when it roams to another AP. It does EAP and EAPOL... ...Is something wrong in config

**Comment by graingert** [comment]
hello, trying to remember back almost a decade ago, when we tried this out all the APs we could find that advertised 802.11r support did not in fact support it

**Comment by graingert** [comment]
I'm going to archive this project soon, here's a gitter room though: https://gitter.im/graingert/802.11r

**Comment by jeetu28** [comment]
Thanks for your reply !! I ll re-cehck the AP again
I hope my configuration is fine.
